/*
Fecha: 26 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: TABLA BITACORA DE USUARIO - SE UTILIZA PARA GUARDAR LOS CAMBIOS DE CLAVE DE CADA USUARIO
*/
create table BITACORA_USUARIO
(
    ID_BUSUARIO number(6),
    FECHA DATE CONSTRAINT BUSUARIO_FECHA_NN NOT NULL,
    CLAVE_ANTERIOR varchar2(20) CONSTRAINT BUSUARIO_CLAVEANT_NN NOT NULL,        
    CLAVE_ACTUAL varchar2(20) CONSTRAINT BUSUARIO_CLAVEACT_NN NOT NULL,        
    ID_USUARIO NUMBER(6), CONSTRAINT FK_USUARIO_BUSUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    --Atributos Auditoria
    Fecha_creacion DATE,
    Usuario_creacion VARCHAR2(10),
    Fecha_ultima_modificacion DATE,
    Usuario_ultima_modificacion VARCHAR2(10)
);

ALTER table BITACORA_USUARIO add constraint pk_BUSUARIO primary key (ID_BUSUARIO)
using index tablespace ce_ind pctfree 20 
storage (initial 10k next 10k pctincrease 0);

---------------------------------------------------------------
--Comentarios de la tabla y atributos
COMMENT ON TABLE BITACORA_USUARIO IS 'TABLA BITACORA DEL USUARIO PARA REGISTRAR LOS CAMBIOS DE CLAVE';
COMMENT ON COLUMN CE.BITACORA_USUARIO.ID_BUSUARIO IS 'IDENTIFICADOR ÚNICO DE LA TABLA';
COMMENT ON COLUMN CE.BITACORA_USUARIO.FECHA IS 'ATRIBUTO DE LA FFECHA EN LA QUE EL USUARIO REALIZÓ EL CAMBIO DE CLAVE ';
COMMENT ON COLUMN CE.BITACORA_USUARIO.CLAVE_ANTERIOR IS 'ATRIBUTO DE LA CLAVE ANTERIOR';
COMMENT ON COLUMN CE.BITACORA_USUARIO.CLAVE_ACTUAL IS 'ATRIBUTO DE LA CLAVE ACTUAL';
COMMENT ON COLUMN CE.BITACORA_USUARIO.ID_USUARIO IS 'ATRIBUTO REFERENCIADO DE LA TABLA USUARIO';

COMMENT ON COLUMN CE.BITACORA_USUARIO.Fecha_creacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.BITACORA_USUARIO.Usuario_creacion IS 'ATRIBUTO AUDITOIA';
COMMENT ON COLUMN CE.BITACORA_USUARIO.Fecha_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.BITACORA_USUARIO.Usuario_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
