/*
Fecha: 24 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: TABLA CATALOGO EVENTO
*/

create table EVENTO
(
    ID_EVENTO number(6),
    NOMBRE varchar2(30) CONSTRAINT EVENTO_NOMBRE_NN NOT NULL, 
    FECHAINICIO DATE CONSTRAINT EVENTO_FECHAI_NN NOT NULL,
    FECHAFIN DATE CONSTRAINT EVENTO_FECHAF_NN NOT NULL,
    LUGAR varchar2(40), 
    ID_ESTADO NUMBER(6), CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
    
    --Atributos Auditoria
    Fecha_creacion DATE,
    Usuario_creacion VARCHAR2(10),
    Fecha_ultima_modificacion DATE,
    Usuario_ultima_modificacion VARCHAR2(10)
);

ALTER table EVENTO add constraint pk_EVENTO primary key (ID_EVENTO)
using index tablespace ce_ind pctfree 20 
storage (initial 10k next 10k pctincrease 0);

---------------------------------------------------------------
--Comentarios de la tabla y atributos
COMMENT ON TABLE EVENTO IS 'CATALOGO EVENTO';
COMMENT ON COLUMN CE.EVENTO.ID_EVENTO IS 'IDENTIFICADOR ÚNICO DE LA TABLA';
COMMENT ON COLUMN CE.EVENTO.NOMBRE IS 'ATRIBUTO CON EL NOMBRE DEL EVENTO';
COMMENT ON COLUMN CE.EVENTO.FECHAINICIO IS 'ATRIBUTO CON LA FECHA DE INICIO DEL EVENTO';
COMMENT ON COLUMN CE.EVENTO.FECHAFIN IS 'ATRIBUTO CON LA FECHA DE FINAL DEL EVENTO';
COMMENT ON COLUMN CE.EVENTO.LUGAR IS 'ATRIBUTO CON EL LUGAR DEL EVENTO';
COMMENT ON COLUMN CE.EVENTO.ID_ESTADO IS 'ATRIBUTO DEL IDENTIFICADOR REFERENCIADO DE LA TABLA ESTADO';

COMMENT ON COLUMN CE.EVENTO.Fecha_creacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.EVENTO.Usuario_creacion IS 'ATRIBUTO AUDITOIA';
COMMENT ON COLUMN CE.EVENTO.Fecha_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.EVENTO.Usuario_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
