/*
Fecha: 26 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: TABLA CONTACTO DE EMERGENCIA
*/
create table CONTACTOEMG
(
    ID_CONTACTOEMG number(6),
    NOMBRE varchar2(20) CONSTRAINT CONTACTOEMG_NOMBRE_NN NOT NULL,    
    APELLIDO varchar2(20),
    TELEFONO varchar2(15) CONSTRAINT CONTACTOEMG_TEL_NN NOT NULL,        
    ID_PERSONA NUMBER(6), CONSTRAINT FK_PERSONACEMG FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    --Atributos Auditoria
    Fecha_creacion DATE,
    Usuario_creacion VARCHAR2(10),
    Fecha_ultima_modificacion DATE,
    Usuario_ultima_modificacion VARCHAR2(10)
);

ALTER table CONTACTOEMG add constraint pk_CONTACTOEMG primary key (ID_CONTACTOEMG)
using index tablespace ce_ind pctfree 20 
storage (initial 10k next 10k pctincrease 0);

---------------------------------------------------------------
--Comentarios de la tabla y atributos
COMMENT ON TABLE CONTACTOEMG IS 'TABLA DE LOS CONTACTOS DE EMERGENCIA DE PERSONA';
COMMENT ON COLUMN CE.CONTACTOEMG.ID_CONTACTOEMG IS 'IDENTIFICADOR ÚNICO DE LA TABLA';
COMMENT ON COLUMN CE.CONTACTOEMG.NOMBRE IS 'ATRIBUTO DEL NOMBRE DEL CONTACTO DE EMERGENCIA';
COMMENT ON COLUMN CE.CONTACTOEMG.APELLIDO IS 'ATRIBUTO CON EL APELLIDO DEL CONTACTO DE EMERGENCIA';
COMMENT ON COLUMN CE.CONTACTOEMG.TELEFONO IS 'ATRIBUTO CON EL TELEFONO DEL CONTACTO DE EMERGENCIA';
COMMENT ON COLUMN CE.CONTACTOEMG.ID_PERSONA IS 'ATRIBUTO REFERENCIADO DE LA TABLA PERSONA';

COMMENT ON COLUMN CE.CONTACTOEMG.Fecha_creacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.CONTACTOEMG.Usuario_creacion IS 'ATRIBUTO AUDITOIA';
COMMENT ON COLUMN CE.CONTACTOEMG.Fecha_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.CONTACTOEMG.Usuario_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
