/*
Fecha: 07 OCTUBRE 2018  
Autor: Mariela Barrantes Mata
Descripcion: Agrega el campo INTERES a la tabla ACTIVIDAD
*/
ALTER TABLE ACTIVIDAD
ADD INTERES DATE;
COMMENT ON COLUMN CE.ACTIVIDAD.INTERES is 'CANTIDAD DE PERSONAS INTERESADAS NO INSCRITAS EN UNA ACTIVIDAD';
