ACTIVIDAD
AXP
BIRACORA AXP
BITACORA USUARIO
CANTON
CONTACTO EMERGENCIA
CORREO
DISTRITO
ESTADO
EVENTO
INSTITUCION
NACIONALIDAD
OCUPACION
PAIS
PERSONA
PROVINCIA
TELEFONO
TIPO PARTICIPANTE
TIPO PERSONA
TIPO PUBLICO
USUARIO


       PROCEDURE INSERTAR_CATALOGO_PROVINCIA(pNombre IN VARCHAR2, pidPais IN NUMBER)
         
       PROCEDURE INSERTAR_CATALOGO_CANTON(pNombre IN VARCHAR2, idProvincia IN NUMBER);

       PROCEDURE INSERTAR_CATALOGO_DISTRITO(pNombre IN VARCHAR2, idCanton IN NUMBER);

       PROCEDURE INSERTAR_CATALOGO_NACIONALIDAD(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_OCUPACION(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_ESTADO(pNombre in varchar2);
       
       PROCEDURE INSERTAR_CATALOGO_TIPOPUBLICO(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_TIPOPERSONA(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_TIPOPARTICIPANTE(pNombre in varchar2);
       
       
       
