/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pry1bd;

/**
 *
 * @author Nakisha Dixon
 */
public class Actividad extends javax.swing.JPanel {

    /**
     * Creates new form Actividad
     */
    public Actividad() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        anio = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        dia = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horaini = new javax.swing.JTextField();
        horafin = new javax.swing.JTextField();
        minutosfin = new javax.swing.JTextField();
        minutosini = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipopublico = new javax.swing.JComboBox<>();
        cupo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lugar = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(null);

        jLabel14.setText("Hora");
        add(jLabel14);
        jLabel14.setBounds(370, 150, 30, 10);

        jLabel15.setText("Minutos");
        add(jLabel15);
        jLabel15.setBounds(410, 150, 40, 14);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 130, 47, 15);

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setForeground(new java.awt.Color(204, 204, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Actividad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1, 21, 520, 40);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(30, 310, 80, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("Listo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 310, 73, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Hora Fin");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 120, 80, 15);

        anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioActionPerformed(evt);
            }
        });
        jPanel1.add(anio);
        anio.setBounds(280, 260, 49, 20);

        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        jPanel1.add(mes);
        mes.setBounds(230, 260, 40, 20);

        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        jPanel1.add(dia);
        dia.setBounds(180, 260, 40, 20);

        jLabel16.setText("Dia");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(200, 240, 15, 10);

        jLabel18.setText("Mes");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(240, 240, 40, 14);

        jLabel20.setText("Año");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(290, 240, 40, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fecha ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 210, 90, 20);

        jLabel21.setText("Hora");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(230, 150, 30, 10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Hora Inicio");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 120, 80, 15);

        jLabel22.setText("Minutos");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(270, 150, 40, 14);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre);
        nombre.setBounds(30, 160, 150, 30);

        jLabel2.setText(":");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 170, 34, 14);

        jLabel4.setText(":");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 170, 4, 14);

        horaini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horainiActionPerformed(evt);
            }
        });
        jPanel1.add(horaini);
        horaini.setBounds(220, 170, 30, 20);

        horafin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horafinActionPerformed(evt);
            }
        });
        jPanel1.add(horafin);
        horafin.setBounds(360, 170, 30, 20);

        minutosfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutosfinActionPerformed(evt);
            }
        });
        jPanel1.add(minutosfin);
        minutosfin.setBounds(420, 170, 30, 20);

        minutosini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutosiniActionPerformed(evt);
            }
        });
        jPanel1.add(minutosini);
        minutosini.setBounds(280, 170, 30, 20);

        jLabel5.setText("Cupo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 210, 34, 14);

        tipopublico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(tipopublico);
        tipopublico.setBounds(40, 240, 100, 20);

        cupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupoActionPerformed(evt);
            }
        });
        jPanel1.add(cupo);
        cupo.setBounds(400, 230, 60, 20);

        jLabel6.setText("Tipo de Publico");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 210, 80, 14);

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(estado);
        estado.setBounds(50, 290, 64, 20);

        jLabel7.setText("Estado");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 270, 33, 14);

        jLabel8.setText("Lugar");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 270, 27, 14);

        lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarActionPerformed(evt);
            }
        });
        jPanel1.add(lugar);
        lugar.setBounds(370, 290, 120, 20);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String datos[] = new String[7];
        String nombres = nombre.getText();
        datos[0]=nombres;
        String dias = dia.getSelectedItem().toString();
        String meses = mes.getSelectedItem().toString();
        String anios = anio.getSelectedItem().toString();
        String fecha = dias+"/"+meses+"/"+anios;
        datos[1]= fecha;
        String horainicio = horaini.getText()+":"+minutosini.getText();
        datos[2]=horainicio;
        String horafinal = horafin.getText()+":"+minutosfin.getText();
        datos[3]= horafinal;
        datos[4]= cupo.getText();
        datos[5]= lugar.getText();
        datos[6]= estado.getSelectedItem().toString();
        datos[7]= tipopublico.getSelectedItem().toString();
        setVisible(false); 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void horainiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horainiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horainiActionPerformed

    private void horafinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horafinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horafinActionPerformed

    private void minutosfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutosfinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutosfinActionPerformed

    private void minutosiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutosiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutosiniActionPerformed

    private void cupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupoActionPerformed

    private void lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anio;
    private javax.swing.JTextField cupo;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField horafin;
    private javax.swing.JTextField horaini;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lugar;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JTextField minutosfin;
    private javax.swing.JTextField minutosini;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> tipopublico;
    // End of variables declaration//GEN-END:variables
}
