/*
Fecha: 02 OCTUBRE 2018
Autor: Mariela Barrantes
Descripcion: INSERT INSTITUCION
*/

INSERTS_TABLAS.INSERTAR_INSTITUCION('ITCR');
INSERTS_TABLAS.INSERTAR_INSTITUCION('UNIVERSIDAD NACIONAL');
INSERTS_TABLAS.INSERTAR_INSTITUCION('UNIVERSIDAD DE COSTA RICA');
INSERTS_TABLAS.INSERTAR_INSTITUCION('UNED');
INSERTS_TABLAS.INSERTAR_INSTITUCION('UNIVERSIDAD LATINA');
INSERTS_TABLAS.INSERTAR_INSTITUCION('UNIVERSIDAD FIDELITAS');
INSERTS_TABLAS.INSERTAR_INSTITUCION('ASAMBLEA LEGISLATIVA');
INSERTS_TABLAS.INSERTAR_INSTITUCION('NETWORK');
INSERTS_TABLAS.INSERTAR_INSTITUCION('INTEL');
INSERTS_TABLAS.INSERTAR_INSTITUCION('AVANTICA');
INSERTS_TABLAS.INSERTAR_INSTITUCION('COMEX');

SELECT * FROM INSTITUCION
