/*
Fecha: 01 OCTUBRE 2018
Autor: Mariela Barrantes
Descripcion: INSERT TIPO PARTICIPANTE
*/

INSERTS_CATALOGO.INSERTAR_CATALOGO_TPARTCPANTE('ESTUDIANTE');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TPARTCPANTE('EXTERNO');


