/* Fecha: 01 OCTUBRE 2018
   Autor: Mariela Barrantes
   Descripcion: INSERTS CATALOGOS*/

select * from PROVINCIA where nombre='COSTA RICA'
INSERTS_CATALOGO.INSERTAR_CATALOGO_PAIS('COSTA RICA');
INSERTS_CATALOGO.INSERTAR_CATALOGO_PAIS('PANAMA');
INSERTS_CATALOGO.INSERTAR_CATALOGO_PAIS('GUATEMALA');
INSERTS_CATALOGO.INSERTAR_CATALOGO_PAIS('ESTADOS UNIDOS');
INSERTS_CATALOGO.INSERTAR_CATALOGO_PAIS('MEXICO');
INSERTS_CATALOGO.INSERTAR_CATALOGO_PAIS('COLOMBIA');

  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('SAN JOSE', 1);--1
  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('ALAJUELA', 1);--2  
  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('CARTAGO',  1);--3
  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('HEREDIA', 1);--4
  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('GUANACASTE', 1);--5
  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('PUNTARENAS', 1);--6 
  INSERTS_CATALOGO.INSERTAR_CATALOGO_PROVINCIA('LIMON', 1);--7



--1 CANTONES SAN JOSE
select * from canton where id_provincia=1
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ACOSTA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ALAJUELITA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ASERRI',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('CURRIDABAT',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('DESAMPARADOS',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('DOTA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ESCAZU',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('GOICOHECHEA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('LEON CORTES CASTRO',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('MONTES DE OCA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('MORA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('MORAVIA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('PEREZ ZELEDON',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('PURISCAL',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN JOSE',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SANTA ANA',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('TARRAZU',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('TIBAS',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('TURRUBARES',1);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('VAZQUEZ DE CORONADO',1);

--2 CANTONES ALAJUELA
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ALAJUELA',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN RAMON',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('GRECIA',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN MATEO',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ATENAS',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('NARANJO',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('PALMARES',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('POAS',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('OROTINA',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN CARLOS',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ZARCERO',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('VALVERDE VEGA',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('UPALA',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('LOS CHILES',2);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('GUATUSO',2);

--3 CANTONES CARTAGO
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('CARTAGO',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('PARAISO',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('LA UNION',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('JIMENEZ',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('TURRIALBA',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ALVARADO',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('OREAMUNO',3);
  INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('EL GUARCO',3);

--4 CANTONES HEREDIA
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('HEREDIA',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('BARVA',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SANTO DOMINGO',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SANTA BARBARA',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN RAFAEL',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN ISIDRO',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('BELEN',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('FLORES',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SAN PABLO',4);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SARAPIQUI',4);

--5 CANTONES GUANACASTE
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('LIBERIA',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('NOCOYA',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SANTA CRUZ',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('BAGACES',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('CARRILLO',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('CAÑAS',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ABANGARES',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('TILARAN',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('NANDAYURE',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('LA CRUZ',5);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('HOJANCHA',5);

--6 CANTONCES PUNTARENAS
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('PUNTARENAS',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('ESPARZA',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('BUENOS AIRES',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('MONTES DE ORO',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('OSA',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('QUEPOS',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('GOLFITO',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('COTO BRUS',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('PARRITA',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('CORREDORES',6);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('GARABITO',6);

--7 CANTONES LIMON
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('LIMON',7);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('POCOCI',7);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('SIQUIRRES',7);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('TALAMANCA',7);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('MATINA',7);
INSERTS_CATALOGO.INSERTAR_CATALOGO_CANTON('GUACIMO',7);


--DISTRITOS SANJOSE
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Ignacio',  1 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Guaitil   '  ,  1 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Palmichal   '  ,  1 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Cangrejal   '  ,  1 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Sabanillas    '  ,  1 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Alajuelita    '  ,  2 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Josecito    '  ,  2 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Antonio   '  ,  2 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Concepción    '  ,  2 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Felipe    '  ,  2 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Aserrí    '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Tarbaca   '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Vuelta de Jorco   '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Gabriel   '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Legua   '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Monterrey   '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Salitrillos   '  ,  3 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Curridabat    '  ,  4 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Granadilla    '  ,  4 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Sánchez   '  ,  4 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Tirrases    '  ,  4 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Desamparados    '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Miguel    '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Juan de Dios    '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Rafael Arriba   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Antonio   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Frailes   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Patarrá   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Cristóbal   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Rosario   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Damas   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Rafael Abajo    '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Gravilias   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Los Guido   '  ,  5 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Santa María   '  ,  6 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Jardín    '  ,  6 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Copey   '  ,  6 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Escazú    '  ,  7 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Antonio   '  ,  7 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Rafael    '  ,  7 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Guadalupe   '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Francisco   '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Calle Blancos   '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Mata de Plátano   '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Ipís    '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Rancho Redondo    '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Purral    '  ,  8 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Pablo   '  ,  9 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Andrés    '  ,  9 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Llano Bonito    '  ,  9 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Isidro    '  ,  9 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Santa Cruz    '  ,  9 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Antonio   '  ,  9 );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Pedro   '  ,  10  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Sabanilla   '  ,  10  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Mercedes    '  ,  10  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Rafael    '  ,  10  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Ciudad Colón    '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Guayabo   '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Tabarcia    '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Piedras Negras    '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Picagres    '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Jaris   '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Quitirrisí    '  ,  11  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Vicente   '  ,  12  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Jerónimo    '  ,  12  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Trinidad    '  ,  12  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Isidro de El General    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' El General    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Daniel Flores   '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Rivas   '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Pedro   '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Platanares    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Pejibaye    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Cajón   '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Barú    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Río Nuevo   '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Páramo    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' La Amistad    '  ,  13  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Santiago    '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Mercedes Sur    '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Barbacoas   '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Grifo Alto    '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Rafael    '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Candelarita   '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Desamparaditos    '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Antonio   '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Chires    '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' La Cangreja   '  ,  14  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Carmen    '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Merced    '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Hospital    '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Catedral    '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Zapote    '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Francisco de Dos Ríos   '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Uruca   '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Mata Redonda    '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Pavas   '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Hatillo   '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Sebastián   '  ,  15  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Santa Ana   '  ,  16  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Salitral    '  ,  16  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Pozos   '  ,  16  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Uruca   '  ,  16  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Piedades    '  ,  16  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Brasil    '  ,  16  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Marcos    '  ,  17  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Lorenzo   '  ,  17  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Carlos    '  ,  17  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Juan    '  ,  18  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Cinco Esquinas    '  ,  18  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Anselmo Llorente    '  ,  18  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' León XIII   '  ,  18  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Colima    '  ,  18  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Pablo   '  ,  19  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Pedro   '  ,  19  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Juan de Mata    '  ,  19  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Luis    '  ,  19  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Carara    '  ,  19  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Isidro    '  ,  20  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' San Rafael    '  ,  20  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Dulce Nombre de Jesús   '  ,  20  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Patalillo   '  ,  20  );
INSERTS_CATALOGO.INSERTAR_CATALOGO_DISTRITO(' Cascajal    '  ,  20  );

