/*
Fecha: 01 OCTUBRE 2018
Autor: Mariela Barrantes
Descripcion: INSERT OCUPACION
*/

INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('ESTUDIANTE');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('INGENIERO');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('MAESTR(A)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('ADMINISTRADOR(A)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('AGENTE DE VENTAS)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('GUARDA DE SEGURIDAD');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('OPERARIO(A)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('ECONOMISTA(O)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('PSICOLOGO(A)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('ARQUITECTA(O)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('BODEGUERO(A)');
INSERTS_CATALOGO.INSERTAR_CATALOGO_OCUPACION('CONTADOR(A)');

