/*
Fecha: 01 OCTUBRE 2018
Autor: Mariela Barrantes
Descripcion: INSERT TIPOPUBLICO
*/

INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('NIÑOS');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('ADOLENTES');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('ADULTOS');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('ADULTOS MAYORES');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('TODO PUBLICO');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('GEEKS');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('TECNICO BÁSICO');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('TECNICO INTERMEDIO');
INSERTS_CATALOGO.INSERTAR_CATALOGO_TIPOPUBLICO('TECNICO AVANZADO');

