/*
Fecha: 30 SETIEMBRE 2018
Autor: Nakisha Dixon
Descripcion: INSERT TABLA ACTXPERSONA: ES DECIR LAS INSCRIPCIONES A UNA ACTIVIDAD
*/

INSERTS_TABLAS.INSERTAR_ACTXPERSONA(3, 1);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(3, 20);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(4, 3);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(4, 20);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(4, 16);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(5, 16);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(5, 17);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(6, 3);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(7, 20);
INSERTS_TABLAS.INSERTAR_ACTXPERSONA(8, 20);
