/*
Fecha: 30 SETIEMBRE 2018
Autor: Nakisha Dixon
Descripcion: INSERT TABLA USUARIO
*/

INSERTS_TABLAS.INSERTAR_USUARIO('Ivan2000', 'ivan2000+', 1);
INSERTS_TABLAS.INSERTAR_USUARIO('adrimiss23', 'adrigamo1998', 2);
INSERTS_TABLAS.INSERTAR_USUARIO('sil.olaf', 'lebon1989', 3);
INSERTS_TABLAS.INSERTAR_USUARIO('caravaca27', 'vaca2791', 4);
INSERTS_TABLAS.INSERTAR_USUARIO('gloria123', 'roglo345',5);
INSERTS_TABLAS.INSERTAR_USUARIO('elsantos+', 'thesantos234', 6);
INSERTS_TABLAS.INSERTAR_USUARIO('MauVale2', 'realvalenciaga123', 7);
INSERTS_TABLAS.INSERTAR_USUARIO('barritaAdri', 'adrianba45', 8);
