--ACT CUPOS LLENANDO 1 3 16 17 20
--SELECT ID_ACTIVIDAD, CUPO FROM ACTIVIDAD WHERE CUPO<8

SELECT * FROM ACTXPERSONA ORDER BY ID_ACTIVIDAD
select * from persona order by id_persona

INSERTS_TABLAS.INSERTAR_ACTXPERSONA(3, 1);

-- 3-6 9-16 personas a inscribir
--16 18 LLENAR POR HORAS
--14 20 LLENAR POR DIAS
