/*
Fecha: 26 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: TABLA ACTIVIDAD X PERSONA - SE UTILIZA PARA LA INSCRIPCION DE UNA PERSONA A UNA ACTIVIDAD
*/
create table BITACORA_AXP
(
    ID_BITACORA NUMBER(6),
    FECHA DATE CONSTRAINT BITACORA_FECHA_NN NOT NULL,
    HORA DATE CONSTRAINT BITACORA_HORA_NN NOT NULL,    
    ID_ACTANTERIOR NUMBER(6),
    ID_ACTACTUAL NUMBER(6) CONSTRAINT BITACORAAXP_ACTACT_NN NOT NULL,
    ID_PERSONA NUMBER(6),
    
    CONSTRAINT FK_BITACORAAXP_AANTPERS FOREIGN KEY (ID_PERSONA, ID_ACTANTERIOR) REFERENCES ACTXPERSONA(ID_PERSONA, ID_ACTIVIDAD),
    
    --Atributos Auditoria
    Fecha_creacion DATE,
    Usuario_creacion VARCHAR2(10),
    Fecha_ultima_modificacion DATE,
    Usuario_ultima_modificacion VARCHAR2(10)
);

ALTER table BITACORA_AXP add constraint pk_BITACORA_AXP primary key (ID_BITACORA)
using index tablespace ce_ind pctfree 20 
storage (initial 10k next 10k pctincrease 0);

---------------------------------------------------------------
--Comentarios de la tabla y atributos
COMMENT ON TABLE BITACORA_AXP IS 'TABLA BITACORA PARA REGISTRAR LOS CAMBIOS DE ACTIVIDADES DE UNA PERSONA';
COMMENT ON COLUMN CE.BITACORA_AXP.ID_BITACORA IS 'IDENTIFICADOR ÚNICO DE LA TABLA';
COMMENT ON COLUMN CE.BITACORA_AXP.FECHA IS 'ATRIBUTO DE LA FECHA DEL CAMBIO DE ACTIVIDAD';
COMMENT ON COLUMN CE.BITACORA_AXP.HORA IS 'ATRIBUTO DE LA HORA DEL CAMBIO DE ACTIVIDAD';
COMMENT ON COLUMN CE.BITACORA_AXP.ID_ACTANTERIOR IS 'ATRIBUTO (REFERENCIADO) DE LA ACTIVIDAD DE LA QUE DESINSCRIBE LA PERSONA';
COMMENT ON COLUMN CE.BITACORA_AXP.ID_ACTANTERIOR IS 'ATRIBUTO (REFERENCIADO) DE LA ACTIVIDAD A LA QUE SE INSCRIBE LA PERSONA';
COMMENT ON COLUMN CE.BITACORA_AXP.ID_PERSONA IS 'ATRIBUTO REFERENCIADO DE LA TABLA ACTIVIDADXPERSONA';

COMMENT ON COLUMN CE.BITACORA_AXP.Fecha_creacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.BITACORA_AXP.Usuario_creacion IS 'ATRIBUTO AUDITOIA';
COMMENT ON COLUMN CE.BITACORA_AXP.Fecha_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.BITACORA_AXP.Usuario_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
