/*
Fecha: 24 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: TABLA CATALOGO PERSONA
*/


create table PERSONA
(
    ID_PERSONA number(6),
    NOMBRE varchar2(20) CONSTRAINT PERSONA_NOMBRE_NN NOT NULL,    
    APELLIDO1 VARCHAR2(15),
    APELLIDO2 VARCHAR2(15),
    NUM_IDENTIFICACION VARCHAR2(15),
    FOTO VARCHAR2(60),
    DIRECCION VARCHAR2(40), --SEÑAS
    ID_DISTRITO NUMBER(6), CONSTRAINT FK_DISTRITO FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO),
    
    ID_NACIONALIDAD NUMBER(6), CONSTRAINT FK_NACIONALIDAD_ID FOREIGN KEY (ID_NACIONALIDAD) REFERENCES NACIONALIDAD(ID_NACIONALIDAD),
    ID_OCUPACION NUMBER(6), CONSTRAINT FK_OCUPACION_ID FOREIGN KEY (ID_OCUPACION) REFERENCES OCUPACION(ID_OCUPACION),
    ID_TPERSONA NUMBER(6), CONSTRAINT FK_TPERSONA FOREIGN KEY (ID_TPERSONA) REFERENCES TIPOPERSONA(ID_TIPOPERSONA),    
    ID_TPARTICIPANTE NUMBER(6), CONSTRAINT FK_TPARTICIPANTE FOREIGN KEY (ID_TPARTICIPANTE) REFERENCES TIPOPARTICIPANTE(ID_TIPOPARTICIPANTE),    
    ID_INSTITUCION NUMBER(6), CONSTRAINT FK_ID_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
            
    --Atributos Auditoria
    Fecha_creacion DATE,
    Usuario_creacion VARCHAR2(10),
    Fecha_ultima_modificacion DATE,
    Usuario_ultima_modificacion VARCHAR2(10)
);

ALTER table PERSONA add constraint pk_PERSONA primary key (ID_PERSONA)
using index tablespace ce_ind pctfree 20 
storage (initial 10k next 10k pctincrease 0);

---------------------------------------------------------------
--Comentarios de la tabla y atributos
COMMENT ON TABLE PERSONA IS 'CATALOGO PERSONA';
COMMENT ON COLUMN CE.PERSONA.ID_PERSONA IS 'IDENTIFICADOR ÚNICO DE LA TABLA';
COMMENT ON COLUMN CE.PERSONA.NOMBRE IS 'ATRIBUTO CON EL NOMBRE DE PERSONA';
COMMENT ON COLUMN CE.PERSONA.APELLIDO1 IS 'ATRIBUTO DEL PRIMER APELLIDO DE PERSONA';
COMMENT ON COLUMN CE.PERSONA.APELLIDO2 IS 'ATRIBUTO DEL SEGUNDO APELLIDO DE PERSONA';
COMMENT ON COLUMN CE.PERSONA.NUM_IDENTIFICACION IS 'ATRIBUTO DEL NUMERO DE IDENTIFICACION DE PERSONA';
COMMENT ON COLUMN CE.PERSONA.FOTO IS 'ATRIBUTO DE LA FOTO DE PERSONA';
COMMENT ON COLUMN CE.PERSONA.DIRECCION IS 'ATRIBUTO DE LOS DETALLES DE LA DIRECCION DE PERSONA';

COMMENT ON COLUMN CE.PERSONA.ID_DISTRITO IS 'ATRIBUTO REFERENCIADO DE LA TABLA DISTRITO';
COMMENT ON COLUMN CE.PERSONA.ID_NACIONALIDAD IS 'ATRIBUTO REFERENCIADO DE LA TABLA NACIONALIDAD';
COMMENT ON COLUMN CE.PERSONA.ID_OCUPACION IS 'ATRIBUTO REFERENCIADO DE LA TABLA OCUPACION';
COMMENT ON COLUMN CE.PERSONA.ID_TPERSONA IS 'ATRIBUTO REFERENCIADO DE LA TABLA TIPO DE PERSONA';
COMMENT ON COLUMN CE.PERSONA.ID_TPARTICIPANTE IS 'ATRIBUTO REFERENCIADO DE LA TABLA TIPO PARTICIPANTE';
COMMENT ON COLUMN CE.PERSONA.ID_INSTITUCION IS 'ATRIBUTO REFERENCIADO DE LA TABLA INSTITUCION';

COMMENT ON COLUMN CE.PERSONA.Fecha_creacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.PERSONA.Usuario_creacion IS 'ATRIBUTO AUDITOIA';
COMMENT ON COLUMN CE.PERSONA.Fecha_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
COMMENT ON COLUMN CE.PERSONA.Usuario_ultima_modificacion IS 'ATRIBUTO AUDITORIA';
