/*
Fecha: 28 SETIEMBRE 2018
Autor: Nakisha Dixon
Descripcion: PAQUETE (ENCABEZADO) Stored Procedures DELETE de las TABLAS CATALOGOS
*/

CREATE OR REPLACE PACKAGE DELETE_CATALOGOS IS
        PROCEDURE DELETE_PAIS(pidPais IN NUMBER); 
        PROCEDURE DELETE_PROVINCIA(pidProvincia IN NUMBER);
        PROCEDURE DELETE_CANTON(pidCanton IN NUMBER);
        PROCEDURE DELETE_DISTRITO(pidDistrito IN NUMBER);
        PROCEDURE DELETE_NACIONALIDAD(pidNacionalidad IN NUMBER);
        PROCEDURE DELETE_OCUPACION(pidOcupacion IN NUMBER);
        PROCEDURE DELETE_ESTADO(pidEstado IN NUMBER);
        PROCEDURE DELETE_TPUBLICO(pidTPublico IN NUMBER);
        PROCEDURE DELETE_TPERSONA(pidTPersona IN NUMBER);
        PROCEDURE DELETE_TPARTIC(pidTPartic IN NUMBER);
 END DELETE_CATALOGOS;
