/*
Fecha: 26 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: PAQUETE (ENCABEZADO) PARA INSERTS DE LAS TABLAS NO CATALOGOS
*/

CREATE OR REPLACE PACKAGE BODY INSERTS_TABLAS IS



END INSERTS_TABLAS;
