/*
Fecha: 26 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: PAQUETE (ENCABEZADO) PARA INSERTS DE LAS TABLAS CATALOGOS
*/

CREATE OR REPLACE PACKAGE INSERTS_CATALOGO IS

       PROCEDURE INSERTAR_CATALOGO_PAIS(pNombre in varchar2);
       
       PROCEDURE INSERTAR_CATALOGO_PROVINCIA(pNombre IN VARCHAR2, pidPais IN NUMBER);

       PROCEDURE INSERTAR_CATALOGO_CANTON(pNombre IN VARCHAR2, pidProvincia IN NUMBER);

       PROCEDURE INSERTAR_CATALOGO_DISTRITO(pNombre IN VARCHAR2, pidCanton IN NUMBER);

       PROCEDURE INSERTAR_CATALOGO_NACIONALIDAD(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_OCUPACION(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_ESTADO(pNombre in varchar2);
       
       PROCEDURE INSERTAR_CATALOGO_TIPOPUBLICO(pDescripcion in varchar2);

       PROCEDURE INSERTAR_CATALOGO_TIPOPERSONA(pNombre in varchar2);

       PROCEDURE INSERTAR_CATALOGO_TPARTCPANTE(pNombre in varchar2);

END INSERTS_CATALOGO;
