/*
Fecha: 26 SETIEMBRE 2018
Autor: Mariela Barrantes
Descripcion: PAQUETE (BODY) PARA INSERTS DE LAS TABLAS CATALOGOS
*/

CREATE OR REPLACE PACKAGE BODY INSERTS_CATALOGO IS

PROCEDURE INSERTAR_CATALOGO_PAIS(pNombre in varchar2)
       AS
       BEGIN
         INSERT INTO PAIS(ID_PAIS, NOMBRE,FECHA_CREACION,USUARIO_CREACION)
         VALUES(SID_PAIS.NEXTVAL, pNombre, SYSDATE, USER);
       END;

 
PROCEDURE INSERTAR_CATALOGO_PROVINCIA(pNombre IN VARCHAR2, pidPais IN NUMBER)
       AS
       BEGIN
         INSERT INTO PROVINCIA(ID_PROVINCIA, NOMBRE, ID_PAIS, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_PROVINCIA.NEXTVAL, pNombre, pidPais, SYSDATE, USER);
       end;  
       
        
PROCEDURE INSERTAR_CATALOGO_CANTON(pNombre IN VARCHAR2, pidProvincia IN NUMBER)
       AS
       BEGIN
         INSERT INTO CANTON(ID_CANTON, NOMBRE, ID_PROVINCIA, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_CANTON.NEXTVAL, pNombre, pidProvincia, SYSDATE, USER);
       end;

       
PROCEDURE INSERTAR_CATALOGO_DISTRITO(pNombre IN VARCHAR2, pidCanton IN NUMBER)
       AS
       BEGIN
         INSERT INTO DISTRITO(ID_DISTRITO, NOMBRE, ID_CANTON, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_DISTRITO.NEXTVAL, pNombre, pidCanton, SYSDATE, USER);
       end;
       
PROCEDURE INSERTAR_CATALOGO_NACIONALIDAD(pNombre in varchar2)
       AS
       BEGIN
         INSERT INTO NACIONALIDAD(ID_NACIONALIDAD, NOMBRE, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_NACIONALIDAD.NEXTVAL, pNombre, SYSDATE, USER);
       end;
       
PROCEDURE INSERTAR_CATALOGO_OCUPACION(pNombre in varchar2)
       AS
       BEGIN
         INSERT INTO OCUPACION(ID_OCUPACION, NOMBRE, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_OCUPACION.NEXTVAL, pNombre, SYSDATE, USER);
       end;

PROCEDURE INSERTAR_CATALOGO_ESTADO(pNombre in varchar2)
       AS
       BEGIN
         INSERT INTO ESTADO(ID_ESTADO, NOMBRE, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_ESTADO.NEXTVAL, pNombre, SYSDATE, USER);
       end;
       
              
PROCEDURE INSERTAR_CATALOGO_TIPOPUBLICO(pDescripcion in varchar2)
       AS
       BEGIN
         INSERT INTO TIPOPUBLICO(ID_TIPOPUBLICO, DESCRIPCION, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_TPUBLICO.NEXTVAL, pDescripcion, SYSDATE, USER);
       end;
       

PROCEDURE INSERTAR_CATALOGO_TIPOPERSONA(pNombre in varchar2)
       AS
       BEGIN
         INSERT INTO TIPOPERSONA(ID_TIPOPERSONA, NOMBRE, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_TPERSONA.NEXTVAL, pNombre, SYSDATE, USER);
       end;
                

PROCEDURE INSERTAR_CATALOGO_TPARTCPANTE(pNombre in varchar2)
       AS
       BEGIN
         INSERT INTO TIPOPARTICIPANTE(ID_TIPOPARTICIPANTE, NOMBRE, FECHA_CREACION, USUARIO_CREACION)
         VALUES(SID_TPARTICIPANTE.NEXTVAL, pNombre, SYSDATE, USER);
       end;

END INSERTS_CATALOGO;
